### ISSUE TITLE
ERR_OPENING_MEDIA: Failed to fetch

### ISSUE THREAD

**Issue by Helioxzsi** [Jenrykster/animeo#1]
Tried to install the addon, but stremio shows: ERR_OPENING_MEDIA: Failed to fetch
![image](https://github.com/Jenrykster/animeo/assets/147111260/a8c3262c-d793-4ad6-974c-75f479702a80)

**Comment by Jenrykster** [comment]
The addon was probably down at the time or the URL was mal-formed, the error means that stremio was not able to get the addon's info.
