### ISSUE TITLE
Issue: Shows with similar names to non-anime shows get logged on anilist

### ISSUE THREAD

**Issue by ObsoletePixel** [Jenrykster/animeo#10]
My partner and I are re-watching The Legend of Korra, and every time we watch an episode, the episode of the same number of The Legend of Zorro gets marked. [See here](https://github.com/Jenrykster/animeo/assets/5619352/94ca3c2b-ee76-4667-a558-c08e0215b7d6)

I'm not sure how you're parsing series name getting watched but it might be worth checking series names to see if a _more_ relevant show matches the name of the show you'd otherwise report watch history to Anilist for.

**Comment by Jenrykster** [comment]
Hi, thanks for reporting the bug.

Currently, I'm using the first result of the anilist search endpoint for the kitsu/cinemeta provided title.

The problem with The Legend of Korra is that it's not present in Anilist's catalog. Searching for it returns The Legend of Zorro (it has the same behavior on the actual website). 

I'm not sure how I'd deal with edge cases like these. But I'm adding two new options to allow better control of the addon(see #7):

1 - Only update media provided by the Kitsu catalog
2 - Only update media that was already in some of your lists (meaning that the addon would not add new entries)

Would any of these options work for you?
