### ISSUE TITLE
Title mismatch even when using Kitsu

### ISSUE THREAD

**Issue by kulaid** [Jenrykster/animeo#11]
This isn't consistent, and I am unsure what can be done, but today, I watched episodes 1 & 2 of Monster (2004). However, the addon marked it on Anilist as "[Golden Kamuy 2nd Season OVA](https://anilist.co/anime/124756/Golden-Kamuy-2nd-Season-OVA/)". Not sure how that could've happened since these 2 shows are very different.

**Comment by Jenrykster** [comment]
Hi, thanks for reporting the bug. It seems that if you search "Monster" on Anilist the first result ends up being the ova of the second season of Golden Kamuy. 
That's very strange... right now the addon is based on the search results but I'll try implementing a more direct way of converting kitsu entries to Anilist.
