### ISSUE TITLE
Mark as watched working?

### ISSUE THREAD

**Issue by icpryde** [Jenrykster/animeo#2]
Does marking an episode as watched also mark it on anilist? i've tried a few different times and I'm not noticing it updating on the anilist page? This is using the Kitsu list.

<img width="403" alt="Screenshot 2023-10-11 at 9 07 42 PM" src="https://github.com/Jenrykster/animeo/assets/29389746/a9180e41-55f9-416f-90c4-1ac797950060">

**Comment by aliyss** [comment]
@icpryde Mark as watched won't work, because animeo uses the subtitle handler to mark it as watched. So it effectively only works when stremio loads the subtitles.

This is a limitation on addons set by stremio at the current state. So there is nothing that can be done on the addon side.

**Comment by Jenrykster** [comment]
Yep, pretty much, I've even asked about it on an open issue on the SDK repo https://github.com/Stremio/stremio-addon-sdk/issues/212#issuecomment-1702879252
