### ISSUE TITLE
Currently playing episode marked as watched

### ISSUE THREAD

**Issue by GitGitu79** [Jenrykster/animeo#4]
Hello, I have an issue where it marked episode that currently playing as watched, and not the one that finished playing.

I'm watching cunibyo demo koi ga sitai, playing episode 10 and then to episode 11, but when I checked my anilist, it marked episode 11 as watched. This continue to happen in episode 12, where I'm still in the beginning of episode and it got marked as complete in anilist, even though it still currently playing.

I'm using Stremio windows 4.4.164 and Torrentio using nyaa

![image](https://github.com/Jenrykster/animeo/assets/152173286/4d947ddc-73b5-4b18-8c70-ea613a1c71cc)
![image](https://github.com/Jenrykster/animeo/assets/152173286/9a0a0617-805f-46e4-a336-e4dd03e88891)

**Comment by Jenrykster** [comment]
Yeah, that's a limitation from stremio, the way this addon works right now is by running when stremio tries to load subtitles (which happens at the start of the playback). Sadly there's no way (at least for now) of detecting when the user actually finishes an episode, so I can't fix it.
