### ISSUE TITLE
Possible Anilist Account Mismatch

### ISSUE THREAD

**Issue by TheGenuineGT** [Jenrykster/animeo#6]
I will occasionally have random anime that I have not watched show up in my Anilist watchlists, particularly only noticing the "Watching" list.

At first I thought this may just be because watching a non-anime show had a similar name to some anime. But Even when not actively watching anything, entries will occasionally show up. Or even when strictly watching anime from Kitsu catalog, a random anime will get added to my "Watching" list.

Example:
Watching Frieren: Beyond Journey's End, episodes will generally update properly. But at some point I would notice Yu Yu Hakusho added and set to Episode 23. Even though I hadn't watched anything else with a similar name.

Issue is not frequent by any means, I've maybe only noticed 3 or 4 instances of this since using your addon. Just thought I would mention, if anyone else may be having this issue.

Unfortunately I don't have any example images of when this occurs.

**Comment by Jenrykster** [comment]
Yeah that is a problem, when I deployed the first version of this addon there was a bug where everyone would be using the account token of the first user but I got rid of it. I'll try debugging it today while I look into issue #5. As always, thanks for the report.

**Comment by Jenrykster** [comment]
I updated the addon to try and fix this issue, please reopen this issue if it happens again.
