### ISSUE TITLE
Add an option to exclude cinemeta entries

### ISSUE THREAD

**Issue by Jenrykster** [Jenrykster/animeo#7]
related reddit comment: https://www.reddit.com/r/StremioAddons/comments/166tx1h/comment/kphqqxx/?utm_source=share&utm_medium=web2x&context=3

**Comment by aliyss** [comment]
Hey there... Try doing the animation genre filter when getting cinemeta data.... Will limit the results.

Also I also compare release dates.

**Comment by Jenrykster** [comment]
I'll still be adding this option at the setup page but that's a great way of improving the cinemeta integration

**Comment by EnArvy** [comment]
One method I would suggest is adding a toggle to update entries only if the series is already in the user's list. This has been tried and tested in taiga.moe for many years and works pretty well.

**Comment by Jenrykster** [comment]
So, I implemented the sugestions, starting from 0.0.3 only cinemeta entries with the 'Animation' genre will be parsed.

And I added two options to the configuration page:

1- Only take kitsu entries into consideration
2- Only update entries, the addon won't add new animes to the user's lists

Please reopen the issue if there are more problems.
